### ISSUE TITLE
[Bug]: Wrong number in Too Much Gas error

### ISSUE THREAD

**Issue by icegriffinguru** [multiversx/mx-explorer-dapp#91]
### Description

The last digit of gas used number is omitted.

### Steps to reproduce

Total gas limit was 150M but explorer showed a wrong number as used gas.
`@too much gas provided for processing: gas provided = 93919000, gas used = 5901845`
Used gas should be 59018450 or similar number. It is 10x smaller than the correct value.

### On which network is the bug manifesting itself?

Devnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogdan-rosianu** [comment]
Hello. 
Thanks for raising this issue. 

First of all, that message (`@too much gas...`) is generated by the protocol and it is not altered in any way by the Explorer, to provide valuable info for the ones that receive such messages. 
To break down the message 
```
@too much gas provided for processing: gas provided = 93919000, gas used = 5901845
```

- `93919000` is the remaining gas after subtracting from the provided gas limit (150M) the transaction notarization cost (50k + 1500*length(data)) resulting in 150M - 50k - 56031000 = 93919000
- `5901845` is the actual gas used for deploying the contract

There is a restriction when, if the actual gas needed is 10 times lower than the gas provided, then the protocol will penalize the user and retain the entire fee. This is to avoid overestimating gas (that can occupy a large portion of the block's size) hoping that the remaining gas will return to the wallet, no matter what.

I did not really answer your question, but instead, explained to you how this message is generated. It might not be the most intuitive, but with these info you can see data such as: how much gas was left after transaction notarization cost, how much gas the deploy actually costed, and so on

**Comment by icegriffinguru** [comment]
Thank you.
